basePath: /
consumes:
    - application/json
definitions:
    Product:
        description: Product defines the structure for an API product
        x-go-package: microservice/data
info:
    description: Documentation for Product API
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            consumes:
                - application/json
            description: Returns a list of products
            operationId: GetProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
                "500":
                    $ref: '#/responses/unableToMarshalJSON'
            tags:
                - products
    /products/{id}:
        delete:
            description: Deletes a product from the database
            operationId: deleteProduct
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - products
produces:
    - application/json
responses:
    noContent:
        description: ""
    productsResponse:
        description: A list of products returned in the response
        schema:
            items: {}
            type: array
schemes:
    - http
swagger: "2.0"
